---
abstract: 'Interface for Thermal (and some dot-matrix and inkjet) Printers that support ESC/POS specification.  '
author:
  - 'Shantanu Bhadoria <shantanu at cpan dott org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0
  List::Util: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Printer-Thermal
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Printer::Thermal:
    file: lib/Printer/Thermal.pm
    version: 0.17
requires:
  Device::SerialPort: 0
  IO::File: 0
  IO::Socket: 0
  Moose: 0
  POSIX: 0
  Time::HiRes: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/shantanubhadoria/printer-thermal/issues
  homepage: https://metacpan.org/release/Printer-Thermal
  repository: git://github.com/shantanubhadoria/printer-thermal.git
version: 0.17
x_contributors:
  - 'Shantanu <shantanu@cpan.org>'
  - 'Shantanu Bhadoria <shantanu dott bhadoria atttt cpan dott org>'
  - 'Shantanu Bhadoria <shantanu.bhadoria@gmail.com>'
  - 'Shantanu Bhadoria <shantanu@cpan.org>'
  - 'Shantanu Bhadoria <shantanu@shantanu-M14xR2.(none)>'
